name: custom_interactive_viewer
description: A highly customizable alternative for Flutter's InteractiveViewer with advanced keyboard navigation, gesture controls, rotation support, and programmatic transformations.
version: 0.0.8
homepage: https://ahnaineh.github.io
repository: https://github.com/ahnaineh/custom_interactive_viewer
issue_tracker: https://github.com/ahnaineh/custom_interactive_viewer/issues

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter: